name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
    build_and_push:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Build application in vm instance
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HYBRID_CICD_HOST_IP }}
            username: ${{ secrets.HYBRID_CICD_HOST_USERNAME }}
            key: ${{ secrets.HYBRID_CICD_HOST_KEY }}
            port: 22
            script: |
                echo "Successfully SSH into the VM Instance"
                
                #? Navigate to the cloned repo
                cd workspace/hybrid-ci-cd-pipeline
                
                #? Checkout to main branch
                git checkout main
                echo "Checkout to main branch"
                
                #? Pull latest changes in this branch
                git pull origin main

                export BUILD_NUMBER=${{ github.run_number }}
                export GCLOUD_ENCODED_SERVICE_ACCOUNT_JSON=${{ secrets.GCLOUD_ENCODED_INFRA_CICD_API_KEY }}
                export GCLOUD_DOCKER_REPO_HOST_NAME=${{ secrets.GCLOUD_DOCKER_REPO_HOSTNAME }}
                export GCLOUD_PROJECT_ID=${{ secrets.GCLOUD_INFRA_CICD_PROJECT_ID }}
                export GCLOUD_DOCKER_REPO_NAME=${{ secrets.GCLOUD_DOCKER_REPO_NAME }}
                export SERVICE_IMAGE_NAME=hybrid-cicd-react
                export TAG_NAME=1.0.$BUILD_NUMBER
                
                #? Build and push docker image to artifact registry
                bash limebrew-ci-scripts/scripts/ci/build-push-docker.sh

                #? Clean build cache
                sudo docker system prune -a --force
                


                
                